---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

    - name: Testing copy of the local remote file
      copy:
        src: ~/project
        dest: /tmp

    - name: "install python for Ansible."
      become: yes
      apt:
        name: "python3-pip"
        state: present
        update_cache: yes
      
  roles:
    - configure-deploy