---

- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: Installing pip
  apt:
    name: "python3-pip"
    state: present
    update_cache: yes

- name: start app
  become: yes
  shell: |
    pwd
    ls

- name: Install project requirements
  become: yes
  pip:
    state: latest
    requirements: "requirements.txt"

# - name: Installs Python libraries from requirements.txt
#   easy_install:
#     name: {{ item }}
#     state: present
#   with_lines: cat "/requirements.txt"

- name: start app
  become: yes
  shell: |
    python app.py