---

- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer requireds
  become: true
  apt:
    autoremove: yes

- name: Installing pip
  apt:
    name: "python3-pip"
    state: present
    update_cache: yes

- name: extract code artifact
  become: yes
  unarchive:
    src: code.tar.gz
    dest: .

- name: Install project requirements
  become: yes
  pip:
    state: latest
    requirements: "/home/ubuntu/root/project/requirements.txt"

- name: start app
  become: yes
  shell: |
    cd /home/ubuntu/root/project/
    sudo python3 app.py >> log.txt 2>&1 &